# finde - based on Zed Dark theme
[colors]
background = "#080A0D"
foreground = "#c6cad7"
cursor = "#FFFFFF"
selection-background = "#515A6A"
selection-foreground = "#c6cad7"

# Regular colors
black = "#080A0D"
red = "#fc6a67"
green = "#a9dc76"
yellow = "#ffd866"
blue = "#739EE8"
magenta = "#fd7df4"
cyan = "#739EE8"
white = "#c6cad7"

# Light/bright colors
light-black = "#404658"
light-red = "#ff6764"
light-green = "#a9f65c"
light-yellow = "#ffd866"
light-blue = "#61eeff"
light-magenta = "#fd7df4"
light-cyan = "#61ffcf"
light-white = "#ffffff"
