model = "gpt-5.2-codex"
model_reasoning_effort = "high"

[projects."/Users/petar/Code"]
trust_level = "trusted"

[projects."/Users/petar/Code/finde-ts"]
trust_level = "untrusted"

[features]
ghost_commit = false
unified_exec = true
apply_patch_freeform = true
web_search_request = true
skills = true
shell_snapshot = true
